### ISSUE TITLE
How to use result returned from where clause

### ISSUE THREAD

**Issue by kingofthebongo2008** [QuantStack/xtl#115]
Hello, 

How I can use the result from where which is std::vector< std::vector<size_t> > for 2d array

auto yx     = xt::where(imap >= t);
auto test   = xt::view(imap, yx);

I get:
error C2440: 'static_cast': cannot convert from 'const S' to 'size_t'

When trying to iterate over it with
auto b = test.cbegin();
auto e = test.cend();

**Comment by JohanMabille** [comment]
Closing this issue since this is related to xtensor.
