### ISSUE TITLE
Add proxy wrapper for iterators

### ISSUE THREAD

**Issue by JohanMabille** [QuantStack/xtl#19]
Proxy iterators cannot return `xclosure_wrapper` and `xclosure_pointer`. Assuming we iterate over elements of following type:
```cpp
struct Iterable
{
    using size_type = std::size_t;
    void operator()(size_type i);
};
```

having `xclosure_wrapper` and `xclosure_pointer` as return type of `operator*` and `operator->` make the following code invalid:

```cpp
auto iter = astruct.begin();
(*it)(1);
using size_type = typename decltype(iter)::size_type;
```

This is because `xclosure_wrapper` wraps the Iterable type and there is no way to propagate types and methods of Iterable.

A solution is to return some type that *inherits* from `Iterable`, so methods and typedefs become available through inheritance mechanism.

**Comment by SylvainCorlay** [comment]
This is a natural issue with any proxy type (optional, property etc...)

Can we mitigate this by having an optional base for the template?

**Comment by JohanMabille** [comment]
I don't think so, that would duplicate the data members of Iterable in the `xclosure_wrapper`.
