### ISSUE TITLE
std::min and std::max for xoptional

### ISSUE THREAD

**Issue by JohanMabille** [QuantStack/xtl#66]
The following fails to compile:

```cpp
using optional = xtl::xoptional<double>;
auto res = std::max(optional(1.2), optional(2.4));
```
because `xoptional<bool, bool>` is not convertible to bool.
A solution is to add an implicit conversion operator from `xoptional<T>` to `T` when `T` is `bool` only, whose implementation can be `return has_value() && value();`

@SylvainCorlay what do you think?

**Comment by SylvainCorlay** [comment]
That would be very very ugly.

**Comment by JohanMabille** [comment]
Ok so let's define `min` and `max` in `xtl` namespace, that will require full qualified calls to these functions though.
