### ISSUE TITLE
Building the tests fails with an ICE on g++ 7.3.1

### ISSUE THREAD

**Issue by HadrienG2** [QuantStack/xtl#71]
Just wanted to inform you that is impossible to build the xtl tests on g++ 7.3.1, as that fails with an internal compiler error. I have checked this for both the latest public release (v0.4.4) and the current master branch.

Like all internal compiler errors, this is not your fault, but that of the compiler. Unfortunately, I do not have enough time to allocate in order to build a minimal reproducer and send it to the g++ team for further investigation. So I will have to leave this up to you.

In any case, you may want to add GCC 7.3 to your CI configurations and to add a workaround for this bug to your codebase, as this GCC version is slowly becoming popular (at least in the projects which I work on).

**Steps to reproduce:**

- Get your hands on a GCC 7.3-based system
- Clone the xtl repo, checkout the 0.4.4 tag or stay on master
- mkdir build && cd build && cmake -DBUILD_TESTS=ON ..
- make

**Expected outcome:**

The tests should build and I should be able to run them.

**What actually happens:**

After a lot of warnings about unsigned -> signed integer conversions, which are likely unrelated to the issue at hand, the build eventually aborts with this message:

    [ 93%] Building CXX object test/CMakeFiles/test_xtl.dir/test_xvariant.cpp.o
    In file included from /home/hadrien/Bureau/Programmation/xtl/include/xtl/xvariant.hpp:17:0,
                     from /home/hadrien/Bureau/Programmation/xtl/test/test_xvariant.cpp:11:
    /home/hadrien/Bureau/Programmation/xtl/include/xtl/xvariant_impl.hpp: In substitution of     ‘template<long unsigned int I, class ... Ts> using type_pack_element_t = typename     mpark::lib::type_pack_element_impl::type::type [with long unsigned int I = I; Ts = {int, float}]    ’:
    /home/hadrien/Bureau/Programmation/xtl/include/xtl/xvariant_impl.hpp:1975:15:   required by     substitution of ‘template<class Arg, typename std::enable_if<(! std::is_same<typename std::decay    <_Tp>::type, mpark::variant<int, float> >::value), int>::type <anonymous>, long unsigned int I,     class T, typename std::enable_if<(std::is_assignable<T&, Arg>::value && std::is_constructible<    T, Arg>::value), int>::type <anonymous> > mpark::variant<int, float>& mpark::variant<int, float>    ::operator=<Arg, <enumerator>, I, T, <enumerator> >(Arg&&) [with Arg = mpark::variant<int, float    >&; typename std::enable_if<(! std::is_same<typename std::decay<_Tp>::type, mpark::variant<int,     float> >::value), int>::type <anonymous> = <missing>; long unsigned int I = <missing>; T = <    missing>; typename std::enable_if<(std::is_assignable<T&, Arg>::value && std::is_constructible<    T, Arg>::value), int>::type <anonymous> = <missing>]’
    /home/hadrien/Bureau/Programmation/xtl/test/test_xvariant.cpp:28:13:   required from here
    /home/hadrien/Bureau/Programmation/xtl/include/xtl/xvariant_impl.hpp:1975:15: internal compiler     error: unexpected expression ‘I’ of kind template_parm_index
                   typename T = lib::type_pack_element_t<I, Ts...>,
                   ^~~~~~~~
    Please submit a full bug report,
    with preprocessed source if appropriate.
    See <http://bugs.opensuse.org/> for instructions.
    make[2]: *** [test/CMakeFiles/test_xtl.dir/build.make:375: test/CMakeFiles/test_xtl.dir/test_    xvariant.cpp.o] Error 1
    make[1]: *** [CMakeFiles/Makefile2:119: test/CMakeFiles/test_xtl.dir/all] Error 2
    make: *** [Makefile:130: all] Error 2

**Comment by wolfv** [comment]
confirmed, i can reproduce on Fedora 27

**Comment by SylvainCorlay** [comment]
😒

**Comment by SylvainCorlay** [comment]
Found a couple of instances of similar ICE for gcc 7.3

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892719
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84785

**Comment by SylvainCorlay** [comment]
> https://gcc.gnu.org/bugzilla/show_bug.cgi?id=84785

The gcc bug listed above looks very very similar with the `type_pack_element_t`, and it appears to have been released upstream.

**Comment by wolfv** [comment]
I think we can close this as it was a compiler bug, right?
